### ISSUE TITLE
Simulation tab

### ISSUE THREAD

**Issue by DavAug** [pkpdapp-team/pkpdapp#50]
Create a demo dash app for the simulation for multiple models (create a new issue for your specific model and reference it below):

- [ ] Model 1: Cancer growth #51
- [x] Model 2: Antibiotics model #52
- [ ] Model 3: Myelotoxicity model #53 

Features:
1. Read dataset as pandas dataframe and allow to plot data in teh figure
2. Take SBML model file, convert it into a myokit model and solve the model
3. Display the solution in the figure
3. Allow to change parameter values with sliders and solve model live. This will need function callback, see https://dash.plotly.com/basic-callbacks
4. Allow change of dosing regimen with sliders (either constant concentration for PD model, or dosing regimen for PK model)
5. Label axes, legend etc appropriately
